### ISSUE TITLE
Grove AI HAT for Edge Computing NOT Supported for Raspberry Pi

### ISSUE THREAD

**Issue by baqwas** [Seeed-Studio/ArduinoCore-k210#11]
Hello!

I'm trying to follow the instructions at http://wiki.seeedstudio.com/Grove_AI_HAT_for_Edge_Computing/ for use with Raspberry Pi. Unfortunately, I cannot complete Step 2.

I specify the Additional Boards Manager URL as URL as 
`https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/master/package_seeeduino_boards_index.json`
and search for K210 in the following screen. The package, Grove AI HAT for Edge Computing by Seeed Studio, is duly displayed (v1.2.0) with an Install button. When I click the Install button 
![Screenshot from 2019-07-11 21-51-35](https://user-images.githubusercontent.com/7071255/61099211-2e5c6e00-a427-11e9-9608-ce2c39c9a965.png) I get the error message in the status bar as **Tool kendryte-standalone is not available for your operating system.**
I have placed the AI HAT on a Raspberry Pi 2B that is running Raspbian Buster.

How can I proceed with the deployed of a suitable package to conduct Arduino development with the AI HAT as described in the Wiki?

Kind regards.

P.S. Here is some information on the Raspberry Pi that I am using:
```
pi@raspbari10:~/Downloads $ uname -a
Linux raspbari10 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux
pi@raspbari10:~/Downloads $


pi@raspbari10:~/Downloads $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
pi@raspbari10:~/Downloads $ 
```

**Comment by Pillar1989** [comment]
Kendryte  is considering this issue and I am sure they will support it soon

**Comment by baqwas** [comment]
Hello!
I am not clear on how the issue can be considered as closed. What is the test verification/validation process?
![Tool kendryte-standalone sdk is not available for your OS](https://user-images.githubusercontent.com/7071255/62081615-a04ef880-b218-11e9-94d6-931458cf4834.png)

Right now, I am trying to install the latest package (i.e. v1.3.0) and the installation fails as follows:
Add the Grove AI HAT board into Arduino IDE.
Click Tools → Board:"xxxx" →Boards Manager, tap K210 into the search bar.
Find the Grove AI HAT for Edge Computing by Seeed Studio, click Install button. 

Please see attached screen shot. FYI, I cannot install v1.2.9 also because it too fails with the same message in the status bar.

I am trying to use the Grove AI HAT for Edge Computing with a Raspberry Pi 2 B+ board. Is this board supported with this HAT? Who has done some testing with this board? Can I have some instructions, please, to repeat the successful test(s)?

Thank you.

**Comment by baqwas** [comment]
I am curious about how the documentation was written if the toolchain support does not exist. Why isn't there a simple statement on the minimum requirements for the boards.
I was simply following written instructions and I thought that I was doing something wrong. I cannot buy Jetson Nano right now if that is the only solution. Please let me know. Thanks.

**Comment by murray1978** [comment]
It is disappointing to see that raspberry pi is not yet supported for the Grove AI HAT for Edge Computing, when it is designed for the Raspberry Pi.

**Comment by baqwas** [comment]
The technical correspondence with Staff (two different companies in the chain) left a lot to be desired from a professionalism perspective. However, to their credit, the Grove Sales "folks" provided a partial credit after several weeks which I applied towards another device just to close out my account.

Kind regards.
