### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by baqwas** [Seeed-Studio/ArduinoCore-k210#14]
Hello!
In the section entitled [Build ArduinoCore-k210 with cmake](https://github.com/Seeed-Studio/ArduinoCore-k210) I ran the suggested script:
```
git clone https://github.com/kendryte/kendryte-standalone-sdk
git clone https://github.com/seeed-Studio/ArduinoCore-k210 kendryte-standalone-sdk/src
```
but I encountered the following error:
```
pi@raspbari9:~/projects/k210 $ git clone https://github.com/kendryte/kendryte-standalone-sdk
Cloning into 'kendryte-standalone-sdk'...
remote: Enumerating objects: 82, done.
remote: Counting objects: 100% (82/82), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 2916 (delta 29), reused 66 (delta 22), pack-reused 2834
Receiving objects: 100% (2916/2916), 5.14 MiB | 2.33 MiB/s, done.
Resolving deltas: 100% (2020/2020), done.
pi@raspbari9:~/projects/k210 $ git clone https://github.com/seeed-Studio/ArduinoCore-k210 kendryte-standalone-sdk/src
fatal: destination path 'kendryte-standalone-sdk/src' already exists and is not an empty directory.
pi@raspbari9:~/projects/k210 $ 
```
What is the workaround or resolution for this error?

Thanks.

**Comment by Pillar1989** [comment]
Refer to https://github.com/Seeed-Studio/ArduinoCore-k210/commit/2ea3c001557c7f70fad560a7a38c57b36b76f321

**Comment by baqwas** [comment]
Thanks, @Pillar1989 

But now with the subsequent step I encounter the following error:
```
pi@raspbari9:~/projects/k210 $ **mkdir build && cd build**
pi@raspbari9:~/projects/k210/build $ **cmake .. -DPROJ=ArduinoCore-k210 -DSKETCH=Blink -DTOOLCHAIN=/opt/kendryte-toolchain/bin**
CMake Error: The source directory "/home/pi/projects/k210" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
pi@raspbari9:~/projects/k210/build $ **cd ..**
pi@raspbari9:~/projects/k210 $ **ls**
_build  kendryte-standalone-sdk_
pi@raspbari9:~/projects/k210 $ **cd kendryte-standalone-sdk**
pi@raspbari9:~/projects/k210/kendryte-standalone-sdk $ **ls**
_CHANGELOG.md  CMakeLists.txt         lds  LICENSE       README.md  src
cmake         kendryte-package.json  lib  package.json  scripts    third_party_
pi@raspbari9:~/projects/k210/kendryte-standalone-sdk $ 
```

Please note that I did the **git clone** operations under _~/projects/k210_ folder- my local convention. Further advice would be appreciated sincerely. Am I correct in assuming that prior to the **mkdir build** command, I should have entered **cd kendryte-standalone-sdk**?

Xie xie.

**Comment by Pillar1989** [comment]
```
pi@raspbari9:~/projects/k210 $ cd  kendryte-standalone-sdk
pi@raspbari9:~/projects/k210 $ mkdir build && cd build
pi@raspbari9:~/projects/k210/build $ cmake .. -DPROJ=ArduinoCore-k210 -DSKETCH=Blink -DTOOLCHAIN=/opt/kendryte-toolchain/bin

```
That's the right thing to do. Try it out and see if you can find the eggs in our files.

**Comment by baqwas** [comment]
@Pillar1989 

Thanks! I've into a problem (see below) because I don't know how to get the correct _toolchain_ installed properly - _the compilers are missing_! Novice mistake on my part, sorry.

```
pi@raspbari9:~ $ cd ~/projects/k210/kendryte-standalone-sdk
pi@raspbari9:~/projects/k210/kendryte-standalone-sdk $ mkdir build
pi@raspbari9:~/projects/k210/kendryte-standalone-sdk $ cd build
pi@raspbari9:~/projects/k210/kendryte-standalone-sdk/build $ cmake .. -DPROJ=ArduinoCore-k210 -DSKETCH=Blink -DTOOLCHAIN=/op/kendryte-toolchain/bin
PROJ = ArduinoCore-k210
-- Check for RISCV toolchain ...
-- Using /op/kendryte-toolchain/bin RISCV toolchain
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is unknown
-- Didn't find assembler
CMake Error at CMakeLists.txt:17 (project):
  The CMAKE_C_COMPILER:

    /op/kendryte-toolchain/bin/riscv64-unknown-elf-gcc

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:17 (project):
  The CMAKE_CXX_COMPILER:

    /op/kendryte-toolchain/bin/riscv64-unknown-elf-g++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:17 (project):
  No CMAKE_ASM_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM" or the CMake cache entry CMAKE_ASM_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Warning: Did not find file Compiler/-ASM
-- Configuring incomplete, errors occurred!
See also "/home/pi/projects/k210/kendryte-standalone-sdk/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/projects/k210/kendryte-standalone-sdk/build/CMakeFiles/CMakeError.log".
pi@raspbari9:~/projects/k210/kendryte-standalone-sdk/build $ 

```

Can you please let me know the names of the packages that I need to install to overcome this basic error? I am using Raspbian Buster and I do believe that **gcc** is installed by default but **asm** - I don't know! :(

Xie xie.

**Comment by Pillar1989** [comment]
@baqwas You've posted three of the same questions on our GitHub, and the essence of these three questions is that kendryte doesn't officially provide Raspbian's ***GCC cross-toolchain***. However, we have never claimed anywhere that we currently support Raspbian systems.

We appreciate your support for our software, but the solution to this problem is not on our side. Please close the other two same issues, so as not to bring unnecessary misleading to others. If the official has support, we will inform you in the first time in this issue. 

I'm sorry I didn't help you. May god bring you luck today.

Duplicate of #13 
Duplicate of #12

**Comment by baqwas** [comment]
@Pillar1989 

So the question (and the issue remains open) is **how is one supposed to use the AI HAT with Raspberry Pi**?

Kendryte will not answer any public post and private letter to management have gone unanswered.

Kind regards.

**Comment by Pillar1989** [comment]
- Grove AI HAT will not work with Raspbian (a la Raspberry PI) even though it is advertised for Raspberry Pi with 40-pin header - not looking for a Raspbian solution but just need some document that I can follow that will let me use the HAT
> Grove AI HAT means it can use the 40-pin header to communicate with raspberry PI, and there's nothing to say that it can be developed with raspberry PI, is that a misunderstanding that we gave you in the documentation?


- Maixduino will not work with Arduino IDE - nothing to do with Raspberry Pi; just looking for a working document on using it as any Arduino compatible board
> What is a Maixduino? Does it matter to us?

- Use Jetson Nano - this will work
>What does it have to do with the Jetson Nano? I believe we didn't mention anything about it in Grove AI HAT's documentation.

**Comment by baqwas** [comment]
@Pillar1989 

Yes, the original Seeed/Grove documentation clearly mentioned Raspberry Pi and that is precisely why I placed the pre-order.

Maixduino is another pre-ordered product where I suspect the USB/serial interface is causing a problem (totally unrelated to AI HAT) but yet another case where Kendryte is being blamed in the Seeed forum in response to my request for help.

Somebody in the Seeed forum mentioned that Jetson Nano would work with AI HAT using some tweaks. Sorry for bringing it up.

I didn't quite understand the reason(s) you have chosen to reply in this manner. You should not be so defensive. I want to work with you to resolve issues even if they are corner cases. Just give me a set of documented test exercises that I can run. Right now I have nothing that works. All the examples that have been published do not work in my situation. I am reporting these as issues in the expectation that perhaps my mistakes on my part can be remedied. I understand that GitHub is not a training/teaching site but I have looked at most of the links on sites related to the boards under consideration and I have yet to find something that works. I concede that the problem is perhaps at my end but I was hoping for a more customer focused response from Seeed.

**Comment by Pillar1989** [comment]
Yes, the original Seeed/Grove documentation clearly mentioned Raspberry Pi and that is precisely why I placed the pre-order.
> Can you point out the wrong document? I don't want it to mislead more people.

Maixduino is another pre-ordered product where I suspect the USB/serial interface is causing a problem (totally unrelated to AI HAT) but yet another case where Kendryte is being blamed in the Seeed forum in response to my request for help.
> Maixduino we cannot provide you with technical support, we just sell products. There is no seeed logo on it, maybe you should go to Kendryte BBS or their  their GitHub to discuss the product.

Somebody in the Seeed forum mentioned that Jetson Nano would work with AI HAT using some tweaks. Sorry for bringing it up.

I didn't quite understand the reason(s) you have chosen to reply in this manner. You should not be so defensive. I want to work with you to resolve issues even if they are corner cases. Just give me a set of documented test exercises that I can run. Right now I have nothing that works. All the examples that have been published do not work in my situation. I am reporting these as issues in the expectation that perhaps my mistakes on my part can be remedied. I understand that GitHub is not a training/teaching site but I have looked at most of the links on sites related to the boards under consideration and I have yet to find something that works. I concede that the problem is perhaps at my end but I was hoping for a more customer focused response from Seeed.
>We have always wanted to help you, and we have never rejected you, but you are very determined to develop this product on raspberry PI. You have three issues, and I have repeatedly answered three times. This issue cannot be developed on raspberry PI, but can only be communicated with raspberry PI, it seems that you have not understood this.
Another way, if you go to Windows or macOS and you have any problems, I will do my best to help you.

**Comment by baqwas** [comment]
@Pillar1989 

I will locate the document that reference Raspberry Pi for the AI HAT and forward it to you later. Will the AI HAT work under Ubuntu?

Please understand that I am **not** determined to follow any rigid path on my own. I simply want to follow instructions. If AI HAT can be used under Ubuntu then I will give it a try. Otherwise I will donate it to someone.

The Maixduino board appears to be defective. I understand that it is not your issue. That is why I contacted Seeed post-sales support for help after posting my issue at the Seeed forum. I will not bother you with Maixduino questions.

**Comment by Pillar1989** [comment]
I will locate the document that reference Raspberry Pi for the AI HAT and forward it to you later. Will the AI HAT work under Ubuntu?
>AI HAT can be developed under x86 ubuntu, and remember, this is not raspberry PI ubuntu. If you have any problems with x86 ubuntu, please let me know and I will help you.

**Comment by baqwas** [comment]
@Pillar1989 

Thanks! I will be using Ubuntu 19.04 (amd64) - nothing to do with any  port or variation for Raspberry Pi (official or unofficial). Yes, I understand that I should not be asking questions about Raspberry Pi here related to the AI HAT (I finally have some sense drilled into my stupid head) at this site. Technical issue closed! But one request, please let Seeed post-sales support (if they contact you again) know that you have nothing to do with Maixduino because Bill seems to think that you have resolved (or perhaps will) my issue for that board too.

Kind regards.

**Comment by baqwas** [comment]
Not an issue for this specific web site but my _limited_ knowledge is in full display at [another site](https://github.com/SeeedDocument/Grove-AI-HAT-for-Edge-Computing/issues)!
