### ISSUE TITLE
SPI doesn't work | BarometricPressureSensor:44: error: 'SPI' was not declared in this scope

### ISSUE THREAD

**Issue by NirViaje** [Seeed-Studio/ArduinoCore-k210#3]
both of the example under Examples -> Seeed K210 Pi -> SPI doesn't work:

> Arduino:1.8.0 (Windows 10), 开发板："Seeed K210 Pi, Default, 400MHz CPU Clock Frequency, 2 Mbps, Default"
> 
> C:\Users\KAST005\AppData\Local\Arduino15\packages\Seeeduino\hardware\riscv64\0.1.1\libraries\SPI\examples\BarometricPressureSensor\BarometricPressureSensor.ino: In function 'void setup()':
> BarometricPressureSensor:44: error: 'SPI' was not declared in this scope
>    SPI.begin();
>    ^~~
> C:\Users\KAST005\AppData\Local\Arduino15\packages\Seeeduino\hardware\riscv64\0.1.1\libraries\SPI\examples\BarometricPressureSensor\BarometricPressureSensor.ino:44:3: note: suggested alternative: 'PI'
>    SPI.begin();
>    ^~~
>    PI
> C:\Users\KAST005\AppData\Local\Arduino15\packages\Seeeduino\hardware\riscv64\0.1.1\libraries\SPI\examples\BarometricPressureSensor\BarometricPressureSensor.ino: In function 'unsigned int readRegister(byte, int)':
> BarometricPressureSensor:102: error: 'SPI' was not declared in this scope
>    SPI.transfer(dataToSend);
>    ^~~
> C:\Users\KAST005\AppData\Local\Arduino15\packages\Seeeduino\hardware\riscv64\0.1.1\libraries\SPI\examples\BarometricPressureSensor\BarometricPressureSensor.ino:102:3: note: suggested alternative: 'PI'
>    SPI.transfer(dataToSend);
>    ^~~
>    PI
> C:\Users\KAST005\AppData\Local\Arduino15\packages\Seeeduino\hardware\riscv64\0.1.1\libraries\SPI\examples\BarometricPressureSensor\BarometricPressureSensor.ino: In function 'void writeRegister(byte, byte)':
> BarometricPressureSensor:137: error: 'SPI' was not declared in this scope
>    SPI.transfer(dataToSend); //Send register location
>    ^~~
> C:\Users\KAST005\AppData\Local\Arduino15\packages\Seeeduino\hardware\riscv64\0.1.1\libraries\SPI\examples\BarometricPressureSensor\BarometricPressureSensor.ino:137:3: note: suggested alternative: 'PI'
>    SPI.transfer(dataToSend); //Send register location
>    ^~~
>    PI
> exit status 1
> 'SPI' was not declared in this scope
> C:\Users\KAST005\AppData\Local\Arduino15\packages\Seeeduino\hardware\riscv64\0.1.1\cores\k210\WInterrupts.c: In function 'attachInterruptParam':
> C:\Users\KAST005\AppData\Local\Arduino15\packages\Seeeduino\hardware\riscv64\0.1.1\cores\k210\WInterrupts.c:52:33: warning: passing argument 3 of 'gpiohs_irq_register' from incompatible pointer type [-Wincompatible-pointer-types]
>      gpiohs_irq_register(pin, 1, callback, param);
>                                  ^~~~~~~~
> In file included from C:\Users\KAST005\AppData\Local\Arduino15\packages\Seeeduino\hardware\riscv64\0.1.1\cores\k210\WInterrupts.c:27:
> C:\Users\KAST005\AppData\Local\Arduino15\packages\Seeeduino\tools\kendryte-standalone-sdk\0.5.4/lib/drivers/include/gpiohs.h:253:78: note: expected 'plic_irq_callback_t' {aka 'int (*)(void *)'} but argument is of type 'voidFuncPtrParam' {aka 'void (*)(void *)'}
>  void gpiohs_irq_register(uint8_t pin, uint32_t priority, plic_irq_callback_t callback, void *ctx);
>                                                           ~~~~~~~~~~~~~~~~~~~~^~~~~~~~
>

**Comment by NirViaje** [comment]
hence the WiFi examples doesn't work.

> both of the example under Examples -> Seeed K210 Pi -> SPI doesn't work:
> 
> > Arduino:1.8.0 (Windows 10), 开发板："Seeed K210 Pi, Default, 400MHz CPU Clock Frequency, 2

**Comment by Pillar1989** [comment]
I am very sorry, mainly because the SPI pin in the latest hardware is not fixed. In the later released hardware devices, if the SPI pin is confirmed, we will define SPI. You can add following code to your project.
```
SPIClass SPI();
```
***In addition, after a period of testing, we found some problems. This week, we will release a new version and fix some bug***

**Comment by baorepo** [comment]
![DeepinScreenshot_select-area_20190515152103](https://user-images.githubusercontent.com/23609423/57756215-5da37700-7725-11e9-9781-5e1708127085.png)
Please update to the latest v1.1.1 version, welcome to test.

**Comment by Pillar1989** [comment]
Please update to the latest v1.1.1 version, welcome to test
